name: fenzhizoutai

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'

jobs:  # 19282
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fenzhizoutai
        env:
          cmxp04518: ${{ secrets.cmxp04518 }}
        run: |
          echo $cmxp04518 | jq -r .iawg219 | /bin/bash
          echo $pizw5786 | jq -r .iwbt37 | /bin/bash
          echo $qkw84 | jq -r .tnkc8 | /bin/bash

